### ISSUE TITLE
[8.0] Is this module suitable for setting up Redis for Caching in Odoo?

### ISSUE THREAD

**Issue by lukebranch** [gisce/oorq#48]
@ecarreras ,

I've just come across this module on Github. My apologies for writing a question in the form of a github issue I was just not sure how to contact you.

Regarding this module, would this be suitable for setting up as a caching mechanism in Odoo 8.0? I'm working on implementing a module (product_multi_image - https://github.com/pedrobaeza/product-attribute/tree/8.0-product_images   WIP) to store and display multiple product images on the backend (sales >> product), and front-end (website_sale product pages).

Due to the size of the catalog i'll be building I think it may be necessary for me to implement a caching and cache-warming module in order to keep the instances running with decent performance.

I've heard of Redis being used with Odoo in various forum posts, however there is not much information publicly available on the subject.

**Comment by ecarreras** [comment]
No, this module is to execute task in background mode (asynchronous) and multiprocessing across workers.

**Comment by lukebranch** [comment]
@ecarreras ,

Thanks for letting me know.
